#yml 파일은 한글사용이 가능하다
hello:
  countries: 대한민국,미국,영국,인도,우즈벡
  account: "{name: '권순길', password: '1234'}"

#application-dev.properties set for devlop env 
spring:
   profiles.active: production
   datasource:
    url: jdbc:h2:mem:demo
   h2:
    console:
      enabled: true
   jpa:
     defer-datasource-initialization: true